# Generated by Django 2.1.5 on 2019-03-07 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
